//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use async_graphql::Enum;
use sea_orm::entity::prelude::*;
use serde::Serialize;
use strum_macros::Display;

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Display, Enum,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stand_stats")]
pub enum StandStats {
    #[sea_orm(string_value = "A")]
    A,
    #[sea_orm(string_value = "B")]
    B,
    #[sea_orm(string_value = "C")]
    C,
    #[sea_orm(string_value = "D")]
    D,
    #[sea_orm(string_value = "E")]
    E,
    #[sea_orm(string_value = "NULL")]
    Null,
}
